{{- if .Values.caCerts.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-certs
  labels:
    {{- include "buildkit.labels" . | nindent 4 }}
binaryData:
  {{- toYaml .Values.caCerts.certs | nindent 2 }}
{{- end }}
