apiVersion: v2
appVersion: v0.9.1
description: Helm chart for buildkit service deployment
icon: https://raw.githubusercontent.com/andrcuns/buildkit-chart/master/charts/buildkit-service/icon.png
maintainers:
- email: andrejs.cunskis@gmail.com
  name: Andrejs Cunskis
name: buildkit-service
type: application
version: 0.0.13
