annotations:
  artifacthub.io/links: |
    - name: source
      url: https://github.com/andrcuns/charts
    - name: support
      url: https://github.com/andrcuns/charts/issues
apiVersion: v2
appVersion: v0.10.4
description: Helm chart for buildkit service deployment
icon: https://raw.githubusercontent.com/andrcuns/buildkit-chart/master/charts/buildkit-service/icon.png
maintainers:
- email: andrejs.cunskis@gmail.com
  name: Andrejs Cunskis
name: buildkit-service
type: application
version: 0.2.2
