---
apiVersion: v2
name: dependabot-gitlab
description: Deployment chart for dependabot-gitlab app
type: application
version: 0.0.71
appVersion: 0.9.1
icon: https://gitlab.com/dependabot-gitlab/dependabot/-/raw/master/logo.png
maintainers:
- name: Andrejs Cunskis
  email: andrejs.cunskis@gmail.com
dependencies:
- name: redis
  version: "~14.7.0"
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: mongodb
  version: "~10.23.0"
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled
