---
apiVersion: v2
appVersion: 0.10.4
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: "~14.7.0"
- condition: mongodb.enabled
  name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: "~10.23.0"
description: Deployment chart for dependabot-gitlab app
icon: https://gitlab.com/dependabot-gitlab/dependabot/-/raw/master/logo.png
maintainers:
- email: andrejs.cunskis@gmail.com
  name: Andrejs Cunskis
name: dependabot-gitlab
type: application
version: 0.0.93
