image:
  # -- Image to use for deploying
  repository: docker.io/andrcuns/dependabot-gitlab
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image tag
  tag: ""

# -- Override chart name
nameOverride: ""
# -- Override fully qualified app name
fullnameOverride: ""

serviceAccount:
  # -- Create service account
  create: false
  # -- Service account annotations
  annotations: {}
  # -- Service account name
  name: ""

service:
  # -- Service type
  type: ClusterIP
  # -- Service pot
  port: 3000
  # -- Service annotations
  annotations: {}

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

# -- Pod annotations
podAnnotations: {}

# -- Node selectors
nodeSelector: {}

# -- Tolerations
tolerations: []

# -- Affinity
affinity: {}

web:
  # -- Web container replicas count
  replicaCount: 1
  # -- Web container resource definitions
  resources: {}
  probes:
    livenessProbe:
      # -- Liveness probe initial delay
      initialDelaySeconds: 10
      # -- Liveness probe failure thresold
      failureThreshold: 20
      # -- Liveness probe period
      periodSeconds: 30
    readinessProbe:
      # -- Readiness probe initial delay
      initialDelaySeconds: 10
      # -- Readiness probe failure threshold
      failureThreshold: 20
      # -- Readiness probe period
      periodSeconds: 30
    startupProbe:
      # -- Start probe initial delay
      initialDelaySeconds: 20
      # -- Start probe failure threshold
      failureThreshold: 20
      # -- Start probe period
      periodSeconds: 5
      # -- Start probe timeout
      timeoutSeconds: 10

worker:
  # -- Worker container replicas count
  replicaCount: 1
  # -- Worker container resource definitions
  resources: {}
  probes:
    livenessProbe:
      # -- Liveness probe initial delay
      initialDelaySeconds: 10
      # -- Liveness probe failure threshold
      failureThreshold: 20
      # -- Liveness probe period
      periodSeconds: 120
    startupProbe:
      # -- Startup probe settings
      initialDelaySeconds: 20
      # -- Startup probe failure threshold
      failureThreshold: 20
      # -- Startup probe period
      periodSeconds: 5
      # -- Startup probe timeout
      timeoutSeconds: 10

env:
  # -- Redis URL
  redisUrl: ""
  # -- MongoDB URL
  mongoDbUrl: ""
  # -- Gitlab instance URL
  gitlabUrl: https://gitlab.com
  # -- Optional sentry dsn for error reporting
  sentryDsn: ""
  # -- Optional app url, used for automated webhook creation
  dependabotUrl: ""

credentials:
  # -- Gitlab access token, required
  gitlab_access_token: ""
  # -- Github access token
  github_access_token: ""
  # -- Gitlab auth token for webhook authentication
  gitlab_auth_token: ""
  # -- Private maven repository credentials, multiple repositories referenced by uniqe name:
  # repoName: {url: url, username: username, password: password}
  maven: {}
  # -- Private npm package registry cretentials, multiple repositories referenced by uniqe name:
  # registryName: {registry: registry, token: token}
  npm: {}
  # -- Private docker registry credentials, multiple repositories referenced by uniqe name:
  # registryName: {registry: registry, username: username, password: password}
  docker: {}

redis:
  # -- Enable redis installation
  enabled: true
  cluster:
    # -- Enable redis cluster
    enabled: false
    # -- Slave count
    slaveCount: 2
  # -- Use redis password
  usePassword: true
  # -- Override redis name
  fullnameOverride: redis
  # -- Kubernetes Cluster Domain
  clusterDomain: cluster.local

mongodb:
  # -- Enable mongodb installation
  enabled: true
  # -- String to fully override mongodb.fullname template
  fullnameOverride: mongodb
  # -- Kubernetes Cluster Domain
  clusterDomain: cluster.local
  auth:
    # -- Enable authentication
    enabled: true
    # -- MongoDB root password
    rootPassword: ""
    # -- MongoDB custom user username
    username: ""
    # -- MongoDB custom user password
    password: ""
    # -- MongoDB custom database
    database: dependabot_gitab
  service:
    # -- Mongodb service port
    port: 27017
