apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dependabot-gitlab.fullname" . }}-worker
  labels:
    {{- include "dependabot-gitlab.labels" . | nindent 4 }}
spec:
  strategy: {{ toYaml .Values.worker.updateStrategy | nindent 4 }}
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "dependabot-gitlab.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "dependabot-gitlab.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
      annotations:
        {{- include "dependabot-gitlab.podAnnotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "dependabot-gitlab.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "dependabot-gitlab.migrationsWaitContainer" . | nindent 8 }}
        {{- include "dependabot-gitlab.redisWaitContainer" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-worker
          {{- include "dependabot-gitlab.image" . | nindent 10 }}
          args:
            - "sidekiq"
          env:
          {{- if or .Values.worker.livenessProbe.enabled .Values.worker.startupProbe.enabled }}
            - name: SIDEKIQ_ALIVE_PORT
              value: {{ .Values.worker.probePort | quote }}
          {{- else }}
            - name: DISABLE_SIDEKIQ_ALIVE
              value: "true"
          {{- end }}
          {{- if .Values.metrics.enabled }}
            - name: PROMETHEUS_EXPORTER_LOG_REQUESTS
              {{- if eq .Values.env.logLevel "debug" }}
              value: "true"
              {{- else }}
              value: "false"
              {{- end }}
            - name: PROMETHEUS_EXPORTER_PORT
              value: {{ .Values.metrics.workerPort | quote }}
          {{- end }}
          {{- with (include "dependabot-gitlab.database-credentials" .) }}
            {{- . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "dependabot-gitlab.fullname" . }}
            - secretRef:
                name: {{ include "dependabot-gitlab.fullname" . }}
          {{- if .Values.metrics.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.workerPort }}
              protocol: TCP
          {{- end }}
          {{- if .Values.worker.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.worker.probePort }}
            failureThreshold: {{ .Values.worker.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.worker.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.worker.livenessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.worker.livenessProbe.enabled }}
          startupProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.worker.probePort }}
            failureThreshold: {{ .Values.worker.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.worker.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.worker.startupProbe.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.worker.startupProbe.initialDelaySeconds }}
          {{- end }}
          lifecycle:
            preStop:
              exec:
                # SIGTERM triggers a quick exit; gracefully terminate instead
                command: ["kube/sidekiq-quiet.sh"]
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      terminationGracePeriodSeconds: 300 # Large dependency files or docker images can take long time to process
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
